# Generated by Django 2.1.4 on 2019-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Auther_Name', models.CharField(max_length=150)),
                ('Number_page', models.IntegerField(default=0)),
                ('date_Publish', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=150)),
            ],
        ),
    ]
