# Generated by Django 2.1.4 on 2019-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_bookstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Auther_Name', models.CharField(max_length=150)),
                ('Number_page', models.IntegerField(default=0)),
                ('date_Publish', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=150)),
                ('Book_Pictuer', models.ImageField(upload_to='lib/static/lib/img')),
                ('Book_File', models.ImageField(upload_to='lib/static/lib/files')),
            ],
        ),
    ]
