# Generated by Django 2.1.4 on 2019-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_File',
            field=models.FileField(upload_to='lib/static/lib/files'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Book_Pictuer',
            field=models.ImageField(blank=True, upload_to='lib/static/lib/img'),
        ),
    ]
