# Generated by Django 2.1.7 on 2019-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20190322_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Auther_Name', models.CharField(max_length=150)),
                ('unversity_Name', models.CharField(default='mustansiriya', max_length=150)),
                ('Number_page', models.IntegerField(default=0)),
                ('date_Publish', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=150)),
                ('Book_Pictuer', models.ImageField(blank=True, upload_to='lib/static/lib/img')),
                ('Book_File', models.FileField(upload_to='lib/static/lib/files')),
            ],
        ),
    ]
