# Generated by Django 2.1.7 on 2019-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_bookmust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookMust',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='BooksTest',
        ),
    ]
