# Generated by Django 2.1.7 on 2019-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0002_auto_20190426_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Book1',
        ),
    ]
