# Generated by Django 2.1.7 on 2019-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBagdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Auther_Name', models.CharField(max_length=150)),
                ('Number_page', models.IntegerField(default=0)),
                ('date_Publish', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=150)),
                ('Book_Pictuer', models.ImageField(blank=True, upload_to='lib/static/lib/img')),
                ('Book_File', models.FileField(upload_to='lib/static/lib/files')),
            ],
        ),
        migrations.CreateModel(
            name='BookBagdad1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=150)),
                ('Auther_Name', models.CharField(max_length=150)),
                ('Number_page', models.IntegerField(default=0)),
                ('date_Publish', models.DateTimeField()),
                ('Publisher', models.CharField(max_length=150)),
                ('Book_Pictuer', models.ImageField(blank=True, upload_to='bagdad/static/bagdad/img')),
                ('Book_File', models.FileField(upload_to='bagdad/static/bagdad/files')),
            ],
        ),
    ]
