# Generated by Django 2.1.7 on 2019-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagdad', '0002_bookbagdad_bookbagdad1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookBagdad',
        ),
        migrations.DeleteModel(
            name='BookBagdad1',
        ),
    ]
